/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToGo */

#ifndef _Included_JavaToGo
#define _Included_JavaToGo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToGo
 * Method:    GoAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JavaToGo_GoAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
